default: &default
  adapter: postgresql
  encoding: unicode
  host: restarone_db
  username: postgres
  password: 1505
  # password: <%= ENV['PG_PASSWORD'] %>
  pool: 5
development:
  <<: *default
  database: HotelManagementWeb_development_1

test:
  <<: *default
  database: HotelManagementWeb_test_1